CREATE TABLE IF NOT EXISTS TASKS (
    ID UUID PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    DUE_DATE DATE CHECK (DUE_DATE >= CURRENT_DATE),
    PRIORITY VARCHAR(10) CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH')),
    COMPLETED BOOLEAN DEFAULT FALSE
);

INSERT INTO TASKS (ID, TITLE, DESCRIPTION, DUE_DATE, PRIORITY, COMPLETED) VALUES
  (RANDOM_UUID(), 'Dummy Task1', 'Dummy Task Desc1', CURRENT_DATE + 1, 'HIGH', false),
  (RANDOM_UUID(), 'Dummy Task2', 'Dummy Task Desc2', CURRENT_DATE + 2, 'MEDIUM', false),
  (RANDOM_UUID(), 'Dummy Task3', 'Dummy Task Desc3', CURRENT_DATE + 5, 'LOW', false),
  (RANDOM_UUID(), 'Dummy Task4', 'Dummy Task Desc4', CURRENT_DATE + 10, 'MEDIUM', true);
